import { Lead, Contact, Company, Deal, Activity, Task, Meeting, Note, Notification, AuditLog, Organization, UserProfile, Employee } from '@/types/crm';

export const initialOrganization: Organization = {
  id: 'org-001',
  name: 'Forge Consultancy',
  slug: 'forge-consultancy',
  established: '2024',
  currency: 'INR',
  currency_symbol: '₹',
  timezone: 'Asia/Kolkata (IST)',
  created_at: '2024-07-28T09:00:00Z',
};

// Official Employee Directory transcribed directly from company roster
export const officialEmployees: Employee[] = [
  // Superiors / Founders
  {
    employee_id: 'FC-01',
    full_name: 'Sarvesh Jeevan',
    email: 'ceo@forgeconsultant.in',
    designation: 'CEO',
    department: 'Founder',
    crm_role: 'Employer/Admin',
    under_team_lead: '— (Board / Founder)',
    responsible_for: 'Executive Strategy & Global Operations',
    joining_date: '28/07/2024',
    employment_status: 'Active',
    is_superior: true,
    password_hint: 'Forge#ceo2024',
  },
  {
    employee_id: 'FC-02',
    full_name: 'Aman Rashid',
    email: 'md@forgeconsultant.in',
    designation: 'MD',
    department: 'Founder',
    crm_role: 'Employer/Admin',
    under_team_lead: '— (Board / Founder)',
    responsible_for: 'Managing Director & Enterprise Growth',
    joining_date: '28/07/2024',
    employment_status: 'Active',
    is_superior: true,
    password_hint: 'Forge#md2024',
  },

  // Team Leads & Leads (Superiors)
  {
    employee_id: 'FC-24',
    full_name: 'Venugopal Naidu K R',
    email: 'venu@forgeconsultant.in',
    designation: 'IT Team Lead',
    department: 'IT',
    crm_role: 'Team Lead',
    under_team_lead: 'Sarvesh Jeevan',
    responsible_for: 'AI Development & Testing Practice',
    joining_date: '04/08/2026',
    employment_status: 'Active',
    is_superior: true,
    password_hint: 'Forge#venu2026',
  },
  {
    employee_id: 'FC-21',
    full_name: 'Sneha Pal',
    email: 'snehapal@forgeconsultant.in',
    designation: 'IT Team and Support Lead',
    department: 'IT',
    crm_role: 'Team Lead',
    under_team_lead: 'Sarvesh Jeevan',
    responsible_for: 'Web Development & other Technical Practice',
    joining_date: '12/06/2026',
    employment_status: 'Active',
    is_superior: true,
    password_hint: 'Forge#sneha2026',
  },
  {
    employee_id: 'FC-34',
    full_name: 'Arun Ekambaram',
    email: 'arunekambaram@forgeconsultant.in',
    designation: 'Performance Test Lead',
    department: 'IT',
    crm_role: 'Team Lead',
    under_team_lead: 'Sarvesh Jeevan',
    responsible_for: 'Performance Test Lead & QA Architecture',
    joining_date: '31/07/2026',
    employment_status: 'Active',
    is_superior: true,
    password_hint: 'Forge#arun2026',
  },
  {
    employee_id: 'FC-47',
    full_name: 'Ambati Madhuvidya Raj',
    email: 'madhuvidya@forgeconsultant.in',
    designation: 'Marketing Lead',
    department: 'Marketing',
    crm_role: 'Lead',
    under_team_lead: 'Aman Rashid',
    responsible_for: 'Marketing Strategy & Brand Growth',
    joining_date: '03/08/2026',
    employment_status: 'Active',
    is_superior: true,
    password_hint: 'Forge#madhuvidya2026',
  },
  {
    employee_id: 'FC-48',
    full_name: 'Kaushik Raj',
    email: 'kaushik@forgeconsultant.in',
    designation: 'Business Management Lead',
    department: 'Management',
    crm_role: 'Lead',
    under_team_lead: 'Sarvesh Jeevan',
    responsible_for: 'Business Development & Enterprise Accounts',
    joining_date: '11/08/2026',
    employment_status: 'Active',
    is_superior: true,
    password_hint: 'Forge#kaushik2026',
  },
  {
    employee_id: 'FC-33',
    full_name: 'Priyanka',
    email: 'priyanka@forgeconsultant.in',
    designation: 'HR Team Documentation',
    department: 'HR',
    crm_role: 'HR',
    under_team_lead: 'Aman Rashid',
    responsible_for: 'HR Operations & Talent Documentation',
    joining_date: '07/08/2026',
    employment_status: 'Active',
    is_superior: true,
    password_hint: 'Forge#priyanka2026',
  },

  // Team Members / Employees
  {
    employee_id: 'FC-15',
    full_name: 'Darshan K',
    email: 'darshan@forgeconsultant.in',
    designation: 'AI Developer',
    department: 'IT',
    crm_role: 'employee',
    under_team_lead: 'Venugopal Naidu K R',
    responsible_for: 'AI Development & Testing',
    joining_date: '04/08/2026',
    employment_status: 'Active',
    is_superior: false,
    password_hint: 'Forge#darshan2026',
  },
  {
    employee_id: 'FC-25',
    full_name: 'Anushree B C',
    email: 'anushree@forgeconsultant.in',
    designation: 'AI Developer',
    department: 'IT',
    crm_role: 'employee',
    under_team_lead: 'Venugopal Naidu K R',
    responsible_for: 'AI Development & Testing',
    joining_date: '31/07/2026',
    employment_status: 'Active',
    is_superior: false,
    password_hint: 'Forge#anushree2026',
  },
  {
    employee_id: 'FC-31',
    full_name: 'Pradeep A',
    email: 'pradeep@forgeconsultant.in',
    designation: 'Backend Developer',
    department: 'IT',
    crm_role: 'employee',
    under_team_lead: 'Arun Ekambaram',
    responsible_for: 'AI Development & Training',
    joining_date: '07/08/2026',
    employment_status: 'Active',
    is_superior: false,
    password_hint: 'Forge#pradeep2026',
  },
  {
    employee_id: 'FC-39',
    full_name: 'Eric Nepolean T',
    email: 'eric@forgeconsultant.in',
    designation: 'Backend Developer',
    department: 'IT',
    crm_role: 'employee',
    under_team_lead: 'Venugopal Naidu K R',
    responsible_for: 'AI Development & Testing',
    joining_date: '04/08/2026',
    employment_status: 'Active',
    is_superior: false,
    password_hint: 'Forge#eric2026',
  },
  {
    employee_id: 'FC-28',
    full_name: 'Pragath R',
    email: 'pragath@forgeconsultant.in',
    designation: 'Cloud Data Analyst',
    department: 'IT',
    crm_role: 'employee',
    under_team_lead: 'Arun Ekambaram',
    responsible_for: 'Deployment & Analysing Data',
    joining_date: '03/08/2026',
    employment_status: 'Active',
    is_superior: false,
    password_hint: 'Forge#pragath2026',
  },
  {
    employee_id: 'FC-37',
    full_name: 'Ayushi Katiyar',
    email: 'ayushi@forgeconsultant.in',
    designation: 'Cyber Security Consultant',
    department: 'IT',
    crm_role: 'employee',
    under_team_lead: 'Arun Ekambaram',
    responsible_for: 'Cybersecurity & Project Security',
    joining_date: '31/07/2026',
    employment_status: 'Active',
    is_superior: false,
    password_hint: 'Forge#ayushi2026',
  },
  {
    employee_id: 'FC-40',
    full_name: 'Charanesh S',
    email: 'charans@forgeconsultant.in',
    designation: 'Data Analyst',
    department: 'IT',
    crm_role: 'employee',
    under_team_lead: 'Venugopal Naidu K R',
    responsible_for: 'AI Development & Testing',
    joining_date: '04/08/2026',
    employment_status: 'Active',
    is_superior: false,
    password_hint: 'Forge#charans2026',
  },
  {
    employee_id: 'FC-42',
    full_name: 'Yash Singh',
    email: 'yashsingh@forgeconsultant.in',
    designation: 'Support Engineer',
    department: 'IT',
    crm_role: 'employee',
    under_team_lead: 'Sneha Pal',
    responsible_for: 'Web Development & other Technical',
    joining_date: '01/08/2026',
    employment_status: 'Active',
    is_superior: false,
    password_hint: 'Forge#yash2026',
  },
  {
    employee_id: 'FC-20',
    full_name: 'Shri Raksha M',
    email: 'shriraksha@forgeconsultant.in',
    designation: 'AI Developer',
    department: 'IT',
    crm_role: 'employee',
    under_team_lead: 'Sneha Pal',
    responsible_for: 'Web Development and AI Development',
    joining_date: '04/08/2026',
    employment_status: 'Active',
    is_superior: false,
    password_hint: 'Forge#shriraksha2026',
  },
  {
    employee_id: 'FC-14',
    full_name: 'Aryan Kumar',
    email: 'aryan@forgeconsultant.in',
    designation: 'Webstack Developer',
    department: 'IT',
    crm_role: 'employee',
    under_team_lead: 'Sneha Pal',
    responsible_for: 'Web Development and other Technical',
    joining_date: '16/06/2026',
    employment_status: 'Active',
    is_superior: false,
    password_hint: 'Forge#aryan2026',
  },
  {
    employee_id: 'FC-43',
    full_name: 'Unnati Singh',
    email: 'unnati@forgeconsultant.in',
    designation: 'Sales Executive',
    department: 'Sales',
    crm_role: 'employee',
    under_team_lead: 'Kaushik Raj',
    responsible_for: 'Client Outreach & Lead Qualification',
    joining_date: '10/08/2026',
    employment_status: 'Active',
    is_superior: false,
    password_hint: 'Forge#unnati2026',
  },
  {
    employee_id: 'FC-32',
    full_name: 'Swapna Sirigiri',
    email: 'swapnamouli@forgeconsultant.in',
    designation: 'HR TEAM Ops',
    department: 'HR',
    crm_role: 'employee',
    under_team_lead: 'Priyanka',
    responsible_for: 'Employee Onboarding & HR Operations',
    joining_date: '07/08/2026',
    employment_status: 'Active',
    is_superior: false,
    password_hint: 'Forge#swapna2026',
  },
  {
    employee_id: 'FC-26',
    full_name: 'Sinchana M R',
    email: 'sinchana@forgeconsultant.in',
    designation: 'AI Database Engineer',
    department: 'IT',
    crm_role: 'employee',
    under_team_lead: 'Venugopal Naidu K R',
    responsible_for: 'AI Development & Testing',
    joining_date: '31/07/2026',
    employment_status: 'Active',
    is_superior: false,
    password_hint: 'Forge#sinchana2026',
  },
  {
    employee_id: 'FC-30',
    full_name: 'Mohammad Ali',
    email: 'ali@forgeconsultant.in',
    designation: 'Marketing Specialist',
    department: 'Marketing',
    crm_role: 'employee',
    under_team_lead: 'Ambati Madhuvidya Raj',
    responsible_for: 'Digital Marketing & Content Campaigns',
    joining_date: '04/08/2026',
    employment_status: 'Active',
    is_superior: false,
    password_hint: 'Forge#ali2026',
  },
  {
    employee_id: 'FC-38',
    full_name: 'Sujay Jain',
    email: 'sujay@forgeconsultant.in',
    designation: 'Backend Developer',
    department: 'IT',
    crm_role: 'employee',
    under_team_lead: 'Arun Ekambaram',
    responsible_for: 'AI Development & Training & Backend',
    joining_date: '04/08/2026',
    employment_status: 'Active',
    is_superior: false,
    password_hint: 'Forge#sujay2026',
  },
  {
    employee_id: 'FC-27',
    full_name: 'Lekhana R',
    email: 'lekhana@forgeconsultant.in',
    designation: 'AI Developer',
    department: 'IT',
    crm_role: 'employee',
    under_team_lead: 'Venugopal Naidu K R',
    responsible_for: 'AI Development & Testing',
    joining_date: '31/07/2026',
    employment_status: 'Active',
    is_superior: false,
    password_hint: 'Forge#lekhana2026',
  },
  {
    employee_id: 'FC-45',
    full_name: 'Mohammad Farman',
    email: 'farman@forgeconsultant.in',
    designation: 'Marketing',
    department: 'Marketing',
    crm_role: 'employee',
    under_team_lead: 'Ambati Madhuvidya Raj',
    responsible_for: 'Lead Generation & Brand Campaigns',
    joining_date: '14/08/2026',
    employment_status: 'Active',
    is_superior: false,
    password_hint: 'Forge#farman2026',
  },
  {
    employee_id: 'FC-39-P',
    full_name: 'Pallavi P',
    email: 'pallavi@forgeconsultant.in',
    designation: 'Marketing Specialist',
    department: 'Marketing',
    crm_role: 'employee',
    under_team_lead: 'Ambati Madhuvidya Raj',
    responsible_for: 'Marketing Strategy & Outreach',
    joining_date: '07/08/2026',
    employment_status: 'Active',
    is_superior: false,
    password_hint: 'Forge#pallavi2026',
  },
];

// Current logged in executive (Sarvesh Jeevan - CEO & Founder)
export const initialUser: UserProfile = {
  id: 'user-fc01',
  name: 'Sarvesh Jeevan',
  email: 'ceo@forgeconsultant.in',
  role: 'admin',
  crm_role: 'Employer/Admin',
  organization_id: 'org-001',
  title: 'Chief Executive Officer (CEO)',
  department: 'Founder',
  employee_id: 'FC-01',
  is_superior: true,
};

export const initialCompanies: Company[] = [
  {
    id: 'comp-001',
    name: 'Titan Logistics & Supply Chain',
    industry: 'Logistics & Infrastructure',
    website: 'https://titanlogistics.in',
    phone: '+91 80 4123 9000',
    email: 'corp@titanlogistics.in',
    address: 'Outer Ring Road',
    city: 'Bengaluru',
    state: 'Karnataka',
    country: 'India',
    employees_count: '2,500 - 5,000',
    annual_revenue: 450000000,
    tier: 'Enterprise',
    owner_id: 'user-fc01',
    owner_name: 'Sarvesh Jeevan',
    description: 'National freight and automated fulfillment network.',
    created_at: '2024-09-10T10:00:00Z',
    updated_at: '2026-08-10T14:30:00Z',
  },
  {
    id: 'comp-002',
    name: 'Apex FinTech Global',
    industry: 'Banking & Financial Services',
    website: 'https://apexfintech.com',
    phone: '+91 22 6789 1234',
    email: 'contact@apexfintech.com',
    address: 'Bandra Kurla Complex (BKC)',
    city: 'Mumbai',
    state: 'Maharashtra',
    country: 'India',
    employees_count: '500 - 1,000',
    annual_revenue: 125000000,
    tier: 'Strategic',
    owner_id: 'user-fc01',
    owner_name: 'Sarvesh Jeevan',
    description: 'High-frequency digital payments processor and neo-banking platform.',
    created_at: '2025-03-01T08:30:00Z',
    updated_at: '2026-08-12T11:20:00Z',
  },
  {
    id: 'comp-003',
    name: 'GreenPulse Renewable Energy',
    industry: 'CleanTech & Energy',
    website: 'https://greenpulse.io',
    phone: '+91 44 2812 5500',
    email: 'info@greenpulse.io',
    address: 'Guindy Industrial Estate',
    city: 'Chennai',
    state: 'Tamil Nadu',
    country: 'India',
    employees_count: '200 - 500',
    annual_revenue: 85000000,
    tier: 'Growth',
    owner_id: 'user-fc01',
    owner_name: 'Venugopal Naidu K R',
    description: 'Commercial solar microgrid operator and IoT energy telemetry.',
    created_at: '2025-04-15T12:00:00Z',
    updated_at: '2026-08-18T16:45:00Z',
  },
  {
    id: 'comp-004',
    name: 'NovaBio Pharmaceuticals',
    industry: 'Healthcare & Life Sciences',
    website: 'https://novabiopharma.in',
    phone: '+91 40 3344 7788',
    email: 'inquiries@novabiopharma.in',
    address: 'Genome Valley, Shamirpet',
    city: 'Hyderabad',
    state: 'Telangana',
    country: 'India',
    employees_count: '1,000 - 2,500',
    annual_revenue: 320000000,
    tier: 'Enterprise',
    owner_id: 'user-fc01',
    owner_name: 'Sarvesh Jeevan',
    description: 'Specialty biosimilars manufacturer with WHO-GMP compliant labs.',
    created_at: '2025-01-20T09:15:00Z',
    updated_at: '2026-08-05T10:00:00Z',
  },
];

export const initialContacts: Contact[] = [
  {
    id: 'cont-001',
    first_name: 'Vikram',
    last_name: 'Malhotra',
    email: 'vikram.malhotra@titanlogistics.in',
    phone: '+91 98450 12345',
    alternate_phone: '+91 80 4123 9011',
    job_title: 'Chief Information Officer',
    company_id: 'comp-001',
    company_name: 'Titan Logistics & Supply Chain',
    address: 'Outer Ring Road',
    city: 'Bengaluru',
    state: 'Karnataka',
    country: 'India',
    owner_id: 'user-fc01',
    owner_name: 'Sarvesh Jeevan',
    tags: ['Decision Maker', 'AI Development', 'VIP'],
    notes: 'Key client executive leading the enterprise AI testing and cloud modernization.',
    created_at: '2025-02-12T11:00:00Z',
    updated_at: '2026-08-14T09:30:00Z',
  },
  {
    id: 'cont-002',
    first_name: 'Ananya',
    last_name: 'Deshmukh',
    email: 'ananya.d@apexfintech.com',
    phone: '+91 98200 98765',
    job_title: 'VP of Digital Strategy',
    company_id: 'comp-002',
    company_name: 'Apex FinTech Global',
    city: 'Mumbai',
    country: 'India',
    owner_id: 'user-fc01',
    owner_name: 'Sarvesh Jeevan',
    tags: ['Champion', 'Cybersecurity', 'Executive'],
    notes: 'Spearheading fraud detection ML algorithms and ISO 27001 compliance.',
    created_at: '2025-03-05T14:20:00Z',
    updated_at: '2026-08-15T16:00:00Z',
  },
  {
    id: 'cont-003',
    first_name: 'Karthik',
    last_name: 'Raman',
    email: 'k.raman@greenpulse.io',
    phone: '+91 97900 45678',
    job_title: 'Chief Operating Officer',
    company_id: 'comp-003',
    company_name: 'GreenPulse Renewable Energy',
    city: 'Chennai',
    country: 'India',
    owner_id: 'user-fc01',
    owner_name: 'Venugopal Naidu K R',
    tags: ['Technical Lead', 'Web Development'],
    notes: 'Assessing Forge Consultancy for telemetry web portal development.',
    created_at: '2025-04-18T10:15:00Z',
    updated_at: '2026-08-17T11:45:00Z',
  },
  {
    id: 'cont-004',
    first_name: 'Dr. Sunita',
    last_name: 'Rao',
    email: 'sunita.rao@novabiopharma.in',
    phone: '+91 94400 11223',
    job_title: 'Director of Enterprise Systems',
    company_id: 'comp-004',
    company_name: 'NovaBio Pharmaceuticals',
    city: 'Hyderabad',
    country: 'India',
    owner_id: 'user-fc01',
    owner_name: 'Sarvesh Jeevan',
    tags: ['Decision Maker', 'Performance Testing'],
    notes: 'Signed off on automated performance testing and load verification.',
    created_at: '2025-01-25T15:00:00Z',
    updated_at: '2026-08-16T12:00:00Z',
  },
];

export const initialLeads: Lead[] = [
  {
    id: 'lead-001',
    first_name: 'Rajesh',
    last_name: 'Sengupta',
    company_name: 'Zenith Retail Chains',
    job_title: 'Chief Technology Officer',
    email: 'r.sengupta@zenithretail.in',
    phone: '+91 98300 22334',
    website: 'https://zenithretail.in',
    location: 'Kolkata, West Bengal',
    industry: 'Retail & E-Commerce',
    lead_source: 'LinkedIn',
    status: 'qualified',
    lead_score: 92,
    estimated_value: 4500000,
    owner_id: 'user-fc01',
    owner_name: 'Kaushik Raj',
    notes: 'Inbound inquiry for full-stack AI development and POS performance testing.',
    ai_summary: 'High-intent enterprise lead with approved Q3 budget for AI & Performance testing.',
    ai_recommended_action: 'Conduct technical scoping session with Venugopal Naidu and Arun Ekambaram.',
    created_at: '2026-08-12T09:00:00Z',
    updated_at: '2026-08-20T14:10:00Z',
  },
  {
    id: 'lead-002',
    first_name: 'Meera',
    last_name: 'Kapoor',
    company_name: 'OmniPay Solutions',
    job_title: 'Head of Risk & Compliance',
    email: 'meera.k@omnipay.io',
    phone: '+91 98110 55667',
    website: 'https://omnipay.io',
    location: 'Gurugram, Haryana',
    industry: 'Banking & Financial Services',
    lead_source: 'Website',
    status: 'contacted',
    lead_score: 78,
    estimated_value: 2800000,
    owner_id: 'user-fc01',
    owner_name: 'Unnati Singh',
    notes: 'Requested consultation on cloud data analysis and cybersecurity audit.',
    ai_summary: 'Fintech compliance deadline in Q4. High demand for security consulting.',
    ai_recommended_action: 'Assign Ayushi Katiyar for cybersecurity posture review.',
    created_at: '2026-08-15T11:30:00Z',
    updated_at: '2026-08-19T10:00:00Z',
  },
  {
    id: 'lead-003',
    first_name: 'Rohan',
    last_name: 'Verma',
    company_name: 'AeroDynamics Aerospace',
    job_title: 'VP of Engineering',
    email: 'rohan.v@aerodynamics.in',
    phone: '+91 99000 88990',
    website: 'https://aerodynamics.in',
    location: 'Bengaluru, Karnataka',
    industry: 'Aerospace & Defense',
    lead_source: 'Referral',
    status: 'new',
    lead_score: 95,
    estimated_value: 6500000,
    owner_id: 'user-fc01',
    owner_name: 'Sarvesh Jeevan',
    notes: 'Direct referral from Titan Logistics. Exploring telemetry data and AI modeling.',
    ai_summary: 'Executive referral with verified budget from board level.',
    ai_recommended_action: 'Direct briefing by Sarvesh Jeevan (CEO) with IT Lead Venugopal Naidu.',
    created_at: '2026-08-21T08:45:00Z',
    updated_at: '2026-08-21T08:45:00Z',
  },
];

export const initialDeals: Deal[] = [
  {
    id: 'deal-001',
    title: 'Titan Global AI Testing & Cloud Modernization',
    company_id: 'comp-001',
    company_name: 'Titan Logistics & Supply Chain',
    contact_id: 'cont-001',
    contact_name: 'Vikram Malhotra',
    amount: 6500000,
    stage: 'negotiation',
    probability: 85,
    expected_close_date: '2026-09-30',
    owner_id: 'user-fc01',
    owner_name: 'Sarvesh Jeevan',
    priority: 'urgent',
    risk_level: 'low',
    service_type: 'AI Development & Testing',
    ai_summary: 'Commercial terms in final review. Scope led by Venugopal Naidu and Arun Ekambaram.',
    notes: 'Final SOW ready for countersigning.',
    created_at: '2026-05-10T10:00:00Z',
    updated_at: '2026-08-20T17:00:00Z',
  },
  {
    id: 'deal-002',
    title: 'Apex FinTech Cybersecurity & ML Advisory',
    company_id: 'comp-002',
    company_name: 'Apex FinTech Global',
    contact_id: 'cont-002',
    contact_name: 'Ananya Deshmukh',
    amount: 4800000,
    stage: 'proposal',
    probability: 60,
    expected_close_date: '2026-10-15',
    owner_id: 'user-fc01',
    owner_name: 'Kaushik Raj',
    priority: 'high',
    risk_level: 'medium',
    service_type: 'Cybersecurity',
    ai_summary: 'Proposal submitted to VP of Strategy. Key focus on real-time neural network fraud audit.',
    created_at: '2026-06-15T11:00:00Z',
    updated_at: '2026-08-18T14:30:00Z',
  },
  {
    id: 'deal-003',
    title: 'NovaBio Performance Testing Suite',
    company_id: 'comp-004',
    company_name: 'NovaBio Pharmaceuticals',
    contact_id: 'cont-004',
    contact_name: 'Dr. Sunita Rao',
    amount: 8500000,
    stage: 'won',
    probability: 100,
    expected_close_date: '2026-08-15',
    owner_id: 'user-fc01',
    owner_name: 'Sarvesh Jeevan',
    priority: 'urgent',
    risk_level: 'low',
    service_type: 'Performance Testing',
    ai_summary: 'Closed enterprise contract. Arun Ekambaram leading sprint execution with QA team.',
    closed_at: '2026-08-15T18:00:00Z',
    created_at: '2026-03-01T09:00:00Z',
    updated_at: '2026-08-15T18:00:00Z',
  },
  {
    id: 'deal-004',
    title: 'GreenPulse Telemetry Webstack Architecture',
    company_id: 'comp-003',
    company_name: 'GreenPulse Renewable Energy',
    contact_id: 'cont-003',
    contact_name: 'Karthik Raman',
    amount: 3200000,
    stage: 'discovery',
    probability: 40,
    expected_close_date: '2026-11-20',
    owner_id: 'user-fc01',
    owner_name: 'Sneha Pal',
    priority: 'medium',
    risk_level: 'low',
    service_type: 'Webstack Development',
    ai_summary: 'Discovery workshops led by Sneha Pal with Aryan Kumar.',
    created_at: '2026-07-20T10:30:00Z',
    updated_at: '2026-08-16T12:00:00Z',
  },
];

export const initialTasks: Task[] = [
  {
    id: 'task-001',
    title: 'Finalize Commercial SOW for Titan Logistics',
    description: 'Review SLA clauses with Sarvesh Jeevan before final client executive signing.',
    due_date: '2026-08-24',
    due_time: '14:00',
    priority: 'urgent',
    status: 'in_progress',
    owner_id: 'user-fc01',
    owner_name: 'Venugopal Naidu K R',
    related_to_type: 'deal',
    related_to_id: 'deal-001',
    related_to_name: 'Titan Global AI Testing & Cloud Modernization',
    created_at: '2026-08-20T10:00:00Z',
  },
  {
    id: 'task-002',
    title: 'Technical Discovery Call with Rajesh Sengupta',
    description: 'Scoping meeting on AI model architecture with Darshan K and Anushree B C.',
    due_date: '2026-08-23',
    due_time: '11:00',
    priority: 'high',
    status: 'not_started',
    owner_id: 'user-fc01',
    owner_name: 'Venugopal Naidu K R',
    related_to_type: 'lead',
    related_to_id: 'lead-001',
    related_to_name: 'Rajesh Sengupta (Zenith Retail)',
    created_at: '2026-08-21T09:30:00Z',
  },
  {
    id: 'task-003',
    title: 'Deliver Performance Test Benchmark Report to NovaBio',
    description: 'Validate high load latency results generated by Pradeep A and Sujay Jain.',
    due_date: '2026-08-26',
    due_time: '15:30',
    priority: 'medium',
    status: 'not_started',
    owner_id: 'user-fc01',
    owner_name: 'Arun Ekambaram',
    related_to_type: 'deal',
    related_to_id: 'deal-003',
    related_to_name: 'NovaBio Performance Testing Suite',
    created_at: '2026-08-19T14:00:00Z',
  },
  {
    id: 'task-004',
    title: 'Cybersecurity Posture Audit for OmniPay Lead',
    description: 'Send compliance frameworks and ISO checklists prepared by Ayushi Katiyar.',
    due_date: '2026-08-22',
    due_time: '17:00',
    priority: 'medium',
    status: 'completed',
    owner_id: 'user-fc01',
    owner_name: 'Kaushik Raj',
    related_to_type: 'lead',
    related_to_id: 'lead-002',
    related_to_name: 'Meera Kapoor (OmniPay)',
    created_at: '2026-08-18T11:00:00Z',
    completed_at: '2026-08-22T16:30:00Z',
  },
];

export const initialActivities: Activity[] = [
  {
    id: 'act-001',
    type: 'meeting',
    title: 'Executive SOW Alignment Meeting',
    description: 'Met with Vikram Malhotra (CIO) to confirm AI testing milestones with Sarvesh Jeevan.',
    entity_type: 'deal',
    entity_id: 'deal-001',
    entity_name: 'Titan Global AI Testing & Cloud Modernization',
    user_id: 'user-fc01',
    user_name: 'Sarvesh Jeevan',
    created_at: '2026-08-21T16:00:00Z',
    duration_minutes: 45,
    outcome: 'Approved with minor SLA tweak',
  },
  {
    id: 'act-002',
    type: 'deal_stage_changed',
    title: 'Deal moved to Negotiation',
    description: 'Moved Titan Global AI Testing from Proposal to Negotiation.',
    entity_type: 'deal',
    entity_id: 'deal-001',
    entity_name: 'Titan Global AI Testing & Cloud Modernization',
    user_id: 'user-fc01',
    user_name: 'Sarvesh Jeevan',
    created_at: '2026-08-20T17:00:00Z',
  },
  {
    id: 'act-003',
    type: 'call',
    title: 'Discovery Scoping Call',
    description: 'Discussed cybersecurity architecture and testing parameters with Ananya Deshmukh.',
    entity_type: 'contact',
    entity_id: 'cont-002',
    entity_name: 'Ananya Deshmukh',
    user_id: 'user-fc01',
    user_name: 'Arun Ekambaram',
    created_at: '2026-08-19T11:30:00Z',
    duration_minutes: 30,
    outcome: 'Sent technical proposal deck',
  },
  {
    id: 'act-004',
    type: 'deal_stage_changed',
    title: 'Deal Closed as WON',
    description: 'Successfully closed NovaBio Performance Testing Suite for ₹85,00,000.',
    entity_type: 'deal',
    entity_id: 'deal-003',
    entity_name: 'NovaBio Performance Testing Suite',
    user_id: 'user-fc01',
    user_name: 'Sarvesh Jeevan',
    created_at: '2026-08-15T18:00:00Z',
  },
];

export const initialMeetings: Meeting[] = [
  {
    id: 'meet-001',
    title: 'AI Development & Testing Architecture Workshop',
    description: 'Led by Venugopal Naidu and team with Titan Logistics engineering leadership.',
    start_time: '2026-08-24T10:00:00Z',
    end_time: '2026-08-24T11:30:00Z',
    location: 'Google Meet',
    meeting_url: 'https://meet.google.com/forge-titan-ai',
    contact_id: 'cont-001',
    contact_name: 'Vikram Malhotra',
    company_name: 'Titan Logistics & Supply Chain',
    deal_id: 'deal-001',
    deal_name: 'Titan Global AI Testing & Cloud Modernization',
    attendees: ['ceo@forgeconsultant.in', 'venu@forgeconsultant.in', 'vikram.malhotra@titanlogistics.in'],
    host_id: 'user-fc01',
    host_name: 'Sarvesh Jeevan',
    status: 'scheduled',
    created_at: '2026-08-20T10:00:00Z',
  },
  {
    id: 'meet-002',
    title: 'Cybersecurity Posture Review',
    description: 'Demonstrating ML fraud detection benchmarks to Apex FinTech.',
    start_time: '2026-08-25T14:30:00Z',
    end_time: '2026-08-25T15:30:00Z',
    location: 'Google Meet',
    meeting_url: 'https://meet.google.com/forge-apex-sec',
    contact_id: 'cont-002',
    contact_name: 'Ananya Deshmukh',
    company_name: 'Apex FinTech Global',
    deal_id: 'deal-002',
    deal_name: 'Apex FinTech Cybersecurity & ML Advisory',
    attendees: ['kaushik@forgeconsultant.in', 'ayushi@forgeconsultant.in', 'ananya.d@apexfintech.com'],
    host_id: 'user-fc01',
    host_name: 'Kaushik Raj',
    status: 'scheduled',
    created_at: '2026-08-21T12:00:00Z',
  },
];

export const initialNotifications: Notification[] = [
  {
    id: 'notif-001',
    title: 'High-Value Deal in Negotiation',
    message: 'Titan Global AI Testing & Cloud Modernization (₹65.00 L) is in final commercial review.',
    type: 'deal',
    read: false,
    link: '/deals',
    created_at: '2026-08-22T08:30:00Z',
  },
  {
    id: 'notif-002',
    title: 'Technical Discovery Workshop Scheduled',
    message: 'Venugopal Naidu has scheduled AI scoping with Rajesh Sengupta (Zenith Retail).',
    type: 'task',
    read: false,
    link: '/calendar',
    created_at: '2026-08-22T10:15:00Z',
  },
  {
    id: 'notif-003',
    title: 'New High Intent Lead',
    message: 'Rohan Verma (VP Engineering, AeroDynamics) assigned to CEO Sarvesh Jeevan.',
    type: 'success',
    read: true,
    link: '/leads',
    created_at: '2026-08-21T08:45:00Z',
  },
];

export const initialAuditLogs: AuditLog[] = [
  {
    id: 'audit-001',
    action: 'Deal Stage Updated',
    entity_type: 'Deal',
    entity_id: 'deal-001',
    entity_title: 'Titan Global AI Testing & Cloud Modernization',
    user_name: 'Sarvesh Jeevan',
    details: 'Moved from Proposal to Negotiation (85% Probability)',
    created_at: '2026-08-20T17:00:00Z',
  },
  {
    id: 'audit-002',
    action: 'Lead Created',
    entity_type: 'Lead',
    entity_id: 'lead-003',
    entity_title: 'Rohan Verma',
    user_name: 'Sarvesh Jeevan',
    details: 'Created lead with score 95 (Referral source)',
    created_at: '2026-08-21T08:45:00Z',
  },
  {
    id: 'audit-003',
    action: 'Deal Closed Won',
    entity_type: 'Deal',
    entity_id: 'deal-003',
    entity_title: 'NovaBio Performance Testing Suite',
    user_name: 'Sarvesh Jeevan',
    details: 'Successfully closed enterprise contract for ₹85,00,000',
    created_at: '2026-08-15T18:00:00Z',
  },
];
